# Generated by Django 6.0.1 on 2026-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_restaurantdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='dishesDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_type', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=100)),
                ('dish_image', models.ImageField(upload_to='dish_images/')),
            ],
        ),
    ]
