# Generated by Django 6.0.1 on 2026-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_dishesdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishesdb',
            name='veg_nonveg',
            field=models.CharField(default='veg', max_length=10),
        ),
    ]
