# Generated by Django 6.0.1 on 2026-02-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdb',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
        ),
    ]
