# Generated by Django 6.0.1 on 2026-02-13 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_contactdb_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
