# Generated by Django 6.0.1 on 2026-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='quantity',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='total_price',
            field=models.IntegerField(max_length=100),
        ),
    ]
