# Generated by Django 6.0.1 on 2026-03-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_cartdb_price_alter_cartdb_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chechoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('totalprice', models.IntegerField(max_length=100)),
            ],
        ),
    ]
